### ISSUE TITLE
Auto Start Option

### ISSUE THREAD

**Issue by jdidit** [cTn-dev/Excavator-GUI#1]
It would be helpful to add an option to start mining job automatically when the program opens. Nicehash has this feature and I found it useful to auto start mining and add Nicehash to Windows Startup. This way, if there is a power failure or the machine reboots for some reason it will resume mining without downtime.

**Comment by cTn-dev** [comment]
Hi, if you start a job and close the app, then start it again, it should resume the previously active job automatically, or does this functionality doesn't work for you?

**Comment by SystemtechCA** [comment]
I can confirm that with my 1070 its resumes mining. Would be nice to add it to windows startup though. I know we can place a shortcut in the startup folder etc but to have control from within the GUI would be a good addition.

**Comment by cTn-dev** [comment]
I will try to look into this in the future, for now you will have to stick with the shortcut method.
Small hint, if you press WIN + R and type in shell:startup, it will take you directly to the user folder.

**Comment by cTn-dev** [comment]
I am happy to inform you that i found a way to implement the auto-start functionality from inside the app, it should land in the release 0.4 and it looks like this (tested only on win10).

![settings](https://user-images.githubusercontent.com/2289413/27963299-e8564910-6334-11e7-920c-4bf7e03f6171.png)

Would this be acceptable?

**Comment by cTn-dev** [comment]
This feature was implemented in 0.4 which was just released, so i am closing this ticket.
Enjoy!
