### ISSUE TITLE
Ethash Alogrithm

### ISSUE THREAD

**Issue by SystemtechCA** [cTn-dev/Excavator-GUI#12]
Im not too sure if Excavator supports it but Nicehash does so i am guessing it does support it, but would be great to be able to mine Eth.
Thanks

PS Loving the app. Been using it full time for the past month or more :)

**Comment by cTn-dev** [comment]
Do you mean Ethereum? There is no algorithm called ethash, Ethereum uses daggerhashimoto and that one is supported both in the miner and the gui from the start.

**Comment by SystemtechCA** [comment]
Here : https://whattomine.com/coins/151-eth-ethash
I will try with daggerhash.
Thanks
