### ISSUE TITLE
Bug - Cannot click any buttons when GPU is missing on overview

### ISSUE THREAD

**Issue by SystemtechCA** [cTn-dev/Excavator-GUI#14]
Hi, So i was swapping some cards and found a really annoying bug. Like REALLY Annoying haha
So i moved a GPU from one rig to another but did not remove it from the Job i was running beforehand.
When i started that rig up again, the GPU was still in the job but full of ??? which is fine, i can just remove it...
wait, why is the remove GPU button not working? in fact no buttons work on the Overview page. On the other pages they seem to work but the overview is completely locked. Cannot add or remove a job, cannot start/stop a job etc. It was so bad that i had to swap that GPU back into this rig, remove it from the job and put it back into the other rig.
Im guessing its a easy fix.
Thanks

**Comment by cTn-dev** [comment]
Hi, thanks for reporting this, i was able to replicate the issue.
It will be fixed in the next version.

**Comment by SystemtechCA** [comment]
Awesome. Thank you very much.

**Comment by cTn-dev** [comment]
Should be fixed in https://github.com/cTn-dev/Excavator-GUI/releases/tag/0.10
