### ISSUE TITLE
GUI not showing realtime stats on latest Excavator (Excavator v1.3.1a)

### ISSUE THREAD

**Issue by Wowowe** [cTn-dev/Excavator-GUI#17]
I've just updated my excavator and this is what I see on the GUI
Its showing inside the excavator that I'm connected and getting shares but on the GUI it shows nothing and I'm disconnected. I don't know whats wrong, hope this would be fix soon.

![image](https://user-images.githubusercontent.com/29969924/31167434-9faf8f7e-a924-11e7-92fc-b47bd24f4366.png)

**Comment by cTn-dev** [comment]
The latest excavator version has made some incompatible changes in the API that's why the GUI doesn't display correctly, ill try to fix it ASAP.

**Comment by cTn-dev** [comment]
The version 0.11 should be compatible with the new API now
