### ISSUE TITLE
Crashing on latest excavator_v1.3.6a

### ISSUE THREAD

**Issue by Wowowe** [cTn-dev/Excavator-GUI#18]
It just wont load properly it keeps restarting and crashing, I hope this would be fixed soon!

![image](https://user-images.githubusercontent.com/29969924/32398416-25bc1872-c12a-11e7-9290-9c4ff94c48d5.png)

**Comment by cTn-dev** [comment]
This is obviously an Excavator issue, since the 1.3.5 works just fine and there were no api changes, nothing i can do on my end.

**Comment by cTn-dev** [comment]
Just a small update (as expected) the 1.3.6a update of Excavator was corrupted, they re-uploaded the files couple of days ago, everything is working fine.
