### ISSUE TITLE
Vertical Resizing

### ISSUE THREAD

**Issue by SystemtechCA** [cTn-dev/Excavator-GUI#4]
Can it be possible to stretch the window vertically. I have 4 GPUS both Dual mining, meaning i have 2 jobs and 8 GPUS visible on the Overview but have to scroll. Can it be made to vertically resize? Then you do not need to take any of the control into account as its just stretching the bottom.

**Comment by cTn-dev** [comment]
Hi, the GUI window should be resize-able (both horizontally and vertically), are you having a problem resizing it vertically? could you please post a screenshot of the bug?

**Comment by SystemtechCA** [comment]
Ok cool. It works on my one PC being able to drag from the edge but not on my other. Only way is to right click the header and choose size, then it works. Both are via teamviewer so that might be part of the problem, but dont worry about.

**Comment by cTn-dev** [comment]
It should also work in team viewer, the "resize icon" wont show when you hover over the window, but you should still be able to resize it.
