### ISSUE TITLE
Save & Load settings! (Enhancement suggestion)

### ISSUE THREAD

**Issue by Wowowe** [cTn-dev/Excavator-GUI#9]
Cause sometimes we do a clean update and completely delete all files and replaced it with new updates, and its hard for us to keep on redoing the same process adding manually our wallets and pools settings etc.

So that when we do a clean update we just replaced the old and load our previous settings! 
I'm sure many would want that.

Unless you can teach us what to do when there's a new update and what files we need to remain so that the settings will be kept.

**Comment by cTn-dev** [comment]
Yup, i can see how this can get rather tedious after a while.
Ill try to implement import/export settings functionality in the future to make updating/upgrading easier.

**Comment by cTn-dev** [comment]
This have been implemented in 0.7 which was just released, enjoy! :-)
